# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Alex Anderson's Website
email: aga@berkeley<.edu>
description: > # this means to ignore newlines until "baseurl:"
    Website for Alex Anderson, a Ph.D. candidate at UC Berkeley in computational neuroscience and machine learning. 
baseurl: "" # the subpath of your site, e.g. /blog
#url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username:  alexanderganderson
linkedin_username: alexanderganderson

# Build settings
markdown: kramdown
